### ISSUE TITLE
Fromatador 0.3.0+ breaks Guard test suite.

### ISSUE THREAD

**Issue by voxik** [geemus/formatador#56]
I observe following test suite errors in Guard:

~~~
$ rspec -rspec_helper -f d spec/lib/guard/dsl_describer_spec.rb 
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 38332

Guard::DslDescriber
  #list
    lists the available Guards declared as strings or symbols (FAILED - 1)
  .notifiers
    properly connects and disconnects
    shows the notifiers and their options (FAILED - 2)
  .show
    shows the Guards and their options

Failures:

  1) Guard::DslDescriber#list lists the available Guards declared as strings or symbols
     Failure/Error: expect(@output).to eq result
     
       expected: "  +---------+-----------+\n  | Plugin  | Guardfile |\n  +---------+-----------+\n  | Another | ✔    ...   | ✘         |\n  | More    | ✘         |\n  | Test    | ✔         |\n  +---------+-----------+\n"
            got: "  +---------+-----------+\n  | Plugin  | Guardfile |\n  +---------+-----------+\n  | Another | ✔    ...en    | ✘        |\n  | More    | ✘        |\n  | Test    | ✔        |\n  +---------+-----------+\n"
     
       (compared using ==)
     
       Diff:
       @@ -1,9 +1,9 @@
          +---------+-----------+
          | Plugin  | Guardfile |
          +---------+-----------+
       -  | Another | ✔         |
       -  | Even    | ✘         |
       -  | More    | ✘         |
       -  | Test    | ✔         |
       +  | Another | ✔        |
       +  | Even    | ✘        |
       +  | More    | ✘        |
       +  | Test    | ✔        |
          +---------+-----------+
     # ./spec/lib/guard/dsl_describer_spec.rb:75:in `block (3 levels) in <top (required)>'

  2) Guard::DslDescriber.notifiers shows the notifiers and their options
     Failure/Error: expect(@output).to eq result
     
       expected: "  +----------------+-----------+------+--------+-------+\n  | Name           | Available | Used | Op...e | ✘         | ✘    |        |       |\n  +----------------+-----------+------+--------+-------+\n"
            got: "  +----------------+-----------+------+--------+-------+\n  | Name           | Available | Used | Op...tle | ✘        | ✘   |        |       |\n  +----------------+-----------+------+--------+-------+\n"
     
       (compared using ==)
     
       Diff:
     
       @@ -1,8 +1,8 @@
          +----------------+-----------+------+--------+-------+
          | Name           | Available | Used | Option | Value |
          +----------------+-----------+------+--------+-------+
       -  | gntp           | ✔         | ✔    | sticky | true  |
       +  | gntp           | ✔        | ✔   | sticky | true  |
          +----------------+-----------+------+--------+-------+
       -  | terminal_title | ✘         | ✘    |        |       |
       +  | terminal_title | ✘        | ✘   |        |       |
          +----------------+-----------+------+--------+-------+
     # ./spec/lib/guard/dsl_describer_spec.rb:163:in `block (3 levels) in <top (required)>'

Finished in 0.04458 seconds (files took 0.10428 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./spec/lib/guard/dsl_describer_spec.rb:73 # Guard::DslDescriber#list lists the available Guards declared as strings or symbols
rspec ./spec/lib/guard/dsl_describer_spec.rb:161 # Guard::DslDescriber.notifiers shows the notifiers and their options

Randomized with seed 38332
~~~

And I'd blame #32 for this, because it makes and assumption that every displayed unicode character occupies two single byte columns. But that is not universal true, as can be seen from this test case leveraging the `unicode` gem:

~~~
$ ruby -runicode -e 'p Unicode.width("✔")'
1

$ ruby -runicode -e 'p Unicode.width("震度")'
4
~~~

Me not being Japanese, I'd propose to revert #32, but yeah, not sure how to make everybody happy:

~~~
$ ruby -runicode -e 'p Unicode.width("🤷")'
1
~~~

**Comment by dreua** [comment]
As I understand it this has been holding up updates of the Fedora package, therefore I'd like to ask whether there are any plans to fix this or help needed.

Furthermore this is not just a broken testsuite but actual broken behavior, I modified the first table example to verify this:

```ruby
table_data = [
  { :name => "Joe",  :food => "Burger" },
  { :name => "Bill", :food => "French fries✘" }
]
Formatador.display_table(table_data)
```
```
With formatador-1.1.1 (installed via gem install formatador)
  +----------------+------+
  | food           | name |
  +----------------+------+
  | Burger         | Joe  |
  +----------------+------+
  | French fries✘ | Bill |
  +----------------+------+

With formatador 0.2.5 (Installed as rpm on Fedora 42)
  +---------------+------+
  | food          | name |
  +---------------+------+
  | Burger        | Joe  |
  +---------------+------+
  | French fries✘ | Bill | [<- this looks fine on the terminal, Github render looks a little off for me]
  +---------------+------+
```

I'd call this a regression. (Assuming that it hasn't been documented as undefined behavior previously.)

Now I don't think #32 should be reverted because that would break the rendering in  other cases but a solution which works for both should be implemented. Would it be so bad to just always require unicode to render those cases correctly? I'd assume that many people around the globe are using multibyte glyphs nowadays, be it language specific or emojis. Not many will realize that they need to load unicode first to fix it.

**Comment by geemus** [comment]
@dreua Thanks for the ping, I didn't realize this was holding something up elsewhere. I'd welcome help and would be happy to see this fixed, but I'm also not sure what the right fix is exactly. Thanks for giving unicode a try at least. I wonder if there are other precedents we could find that might have a solution, as it seems like surely we aren't the first people to come across this.

**Comment by geemus** [comment]
I tried to explore if https://ruby-doc.org/core-3.1.1/String.html#method-i-grapheme_clusters might help, but if so it wasn't immediately apparent, but thought I would call it out in case it landed more for you than me...

**Comment by dreua** [comment]
I think the grapheme clusters are only the first step, the second would be to calculate their widths. Putting that into a search engine, I actually found `Reline::Unicode.calculate_width("🎉")` which seems to work quite well.

I'm not exactly sure how, but it is available on my machine without any package of that name installed, probably baked into ruby or irb?

**Comment by dreua** [comment]
Alright, in Fedora it is shipped in the `ruby-default-gems` package and according to https://stdgems.org/ reline is actually part of the default gems and can be expected to be available everywhere where ruby runs. I think this is the perfect solution for formatador!

**Comment by dreua** [comment]
I'm not a ruby developer unfortunately, so I'd need to find some time to get up to speed with the environment and language. Not sure I can do that in a timely manner. The PR looks good to me and quite straightforward, but I do understand that some tests would be good to have. (Maybe someone else can come to help with that quicker than me 🤔 )

**Comment by geemus** [comment]
That should be released in v1.2.0.

**Comment by geemus** [comment]
Got it, thanks for the heads up!
